name: tealium_moments_api
description: A new Flutter plugin for using Tealium's Moments API Module with the Tealium Flutter Plugin.
version: 2.0.0
homepage: https://docs.tealium.com/platforms/flutter/

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  tealium: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tealium.flutter.moments_api.tealium_moments_api
        pluginClass: TealiumMomentsApiPlugin
      ios:
        pluginClass: TealiumMomentsApiPlugin
