name: tealium_adobevisitor_example
description: Demonstrates how to use the tealium_adobevisitor plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tealium_adobevisitor:
    path: ../
  tealium:
    path: ../../../tealium/
  cupertino_icons: ^1.0.2

dependency_overrides:
  tealium:
    path: ../../../tealium/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
